-- MySQL Script generated by MySQL Workbench
-- Mon May 14 14:54:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `unit` VARCHAR(255) NOT NULL,
  `stock` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))



-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suppliers` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))


-- -----------------------------------------------------
-- Table `mydb`.`product_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_supplier` (
  `products_id` INT NOT NULL,
  `suppliers_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `suppliers_id`),
  INDEX `fk_products_has_suppliers_suppliers1_idx` (`suppliers_id` ASC),
  INDEX `fk_products_has_suppliers_products_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_has_suppliers_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_suppliers_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
